---
title: 'Encuentro 3 - Código Abierto'
teaching: 10
exercises: 2
---

En este tercer encuentro hablaremos sobre qué es el software de código abierto, distintas herramientas para facilitar su apertura y cómo gestionarla desde el principio mediante un Plan de Gestión de Software (PGS). También hablaremos de buenas prácticas para que nuestro código sea fácil de encontrar, accesible y reutilizable; así como para reusar código generado por otras personas. 

## Objetivos del Encuentro 3

1. Explicar qué significa el software de Código Abierto, enumerar sus beneficios y desafíos
2. Explorar los componentes de un Plan de Gestión de Software de Código Abierto
3. Compartir recomendaciones y buenas prácticas para trabajar con Código Abierto
 

## Cronograma

|  Hora | Actividad | Duración |
| ---:  | :----------- | :----------- |
|-00:15 | Tiempo previo para conectarse | 
|00:00 | Bienvenida e información general | 15 mins |
|00:15 | Bloque 1. ¿Qué es el software de Código Abierto? | 5 mins |
|00:20 | Principios del Código Abierto | 10 mins |
|00:30 | Ejercicio 1. Encuesta de Zoom | 5 mins |
|00:35 | Plan de gestión de software | 5 mins |
|00:40 | ¿Qué, cuándo y dónde compartir? | 10 mins |
|00:50 | Ejercicio 2. Actividad en grupo  | 15 mins |
|01:05 | Recapitulando | 2 mins |
|01:07 | *Pausa* | 10 mins |
|01:17 | Bloque 2. Control de versiones | 10 mins |
|01:27 | Integración GitHub + Zenodo | 10 mins |
|01:37 | Ejercicio 3. Encuesta de Zoom | 5 mins |
|01:42 | ¿Cómo compartir? ¿Quiénes participan? - Ejemplo | 10 mins |
|01:52 | Reusar Código Abierto | 10 mins |
|02:02 | Ejercicio 4. Encuesta de Zoom | 5 mins |
|02:07 | Encuesta anónima de valoración | 5 mins |
|02:12 | Evaluación de contenidos para la certificación | 15 mins |
|02:27 | Cierre | 3 mins |

## Materiales

- [Presentación](https://doi.org/10.5281/zenodo.18894415)
 
### ¡Sírvete sin culpa!

Nuestros materiales están disponibles en forma gratuita bajo esta [licencia](https://creativecommons.org/licenses/by/4.0/deed.es). Es decir, puedes reusar o editar cualquier material que aparece acá, lo único que pedimos a cambio es que cuando tomes material de acá incluyas una referencia a esta página web.
