---
title: 'Encuentro 4 - Resultados Abiertos'
teaching: 10
exercises: 2
---

Este cuarto encuentro busca profundizar sobre las distintas formas de publicar resultados abiertos, herramientas que pueden ayudarnos a gestionar la apertura de proyectos de investigación y buenas prácticas para la generación de reportes acordes a los principios FAIR. 


## Objetivos del Encuentro 4

1. Conocer cómo compartir en abierto para su reusabilidad y reproducibilidad
2. Explorar distintas formas de colaborar y gestionar reconocimiento
3. Presentar plataformas disponibles para publicar Resultados Abiertos
4. Compartir estrategias de apertura posibles, reflexionar sobre las preocupaciones y obstáculos a la hora de abrir resultados y sus formas de mitigación
5. Analizar los contenidos trabajados a lo largo del curso usando un caso real
 
## Cronograma

|  Hora | Actividad | Duración |
| ---:  | :----------- | :----------- |
|-00:15 | Tiempo previo para conectarse | 
|00:00 |	Bienvenida	| 10 min |
|00:10 |	Resultados del proceso de investigación	| 5 min |
|00:15 |	Ejercicio 1	| 5 min |
|00:20 |	Formas de colaborar, roles y reconocimiento | 10 min |
|00:30 |	Publicaciones de acceso abierto	| 10 min |
|00:40 |	Ejercicio 2	| 5 min |
|00:45 |	Revistas predatorias	| 5 min |
|00:50 |	Pre-prints	| 5 min |
|00:55 |	Recapitulando	| 2 min |
|00:57 |	Pausa	| 10 min |
|01:07 |	Registro de proyectos	| 5 min |
|01:12 |	Software de gestión de referencias	| 5 min |
|01:17 |	Ejercicio 3	| 13 min |
|01:30 |	Planificar para abrir	| 20 min |
|01:50 |	El caso de la EPH	| 5 min |
|01:55 |	Ejercicio 4	| 5 min |
|02:00 |	Ciencia Abierta e Inteligencia Artificial	| 5 min |
|02:05 |	Recapitulando	| 2 min |
|02:07 |	Encuesta anónima	| 5 min |
|02:12 |	Evaluación del encuentro	| 10 min |
|02:22 |	Información sobre certificación	| 5 min |
|02:27 |	Cierre	| 3 min |

## Materiales

- [Presentación](https://doi.org/10.5281/zenodo.18894630)

  
### ¡Sírvete sin culpa!
Nuestros materiales están disponibles en forma gratuita bajo esta [licencia](https://creativecommons.org/licenses/by/4.0/deed.es). Es decir, puedes reusar o editar cualquier material que aparece acá, lo único que pedimos a cambio es que cuando tomes material de acá incluyas una referencia a esta página web.
